### ISSUE TITLE
Upgrade to Android V2 embedding

### ISSUE THREAD

**Issue by QuirijnGB** [uxcam/flutter-plugin#1]
V1 embedding is deprecated: 
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by andre-paraense** [comment]
Yes, when using Flutter 2.5, we already get warnings about this:

`The plugin `flutter_uxcam` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.`
