### ISSUE TITLE
Performance issues on Android

### ISSUE THREAD

**Issue by Amir-P** [uxcam/flutter-plugin#5]
We have decided to remove this plugin from our project due to its effect on app performance on Android devices. We were experiencing frame drop in large lists while scrolling which went away after removing the plugin. Right now I don't have enough time to provide more info regarding this issue.

**Comment by gabmadera** [comment]
Hi @Amir-P the flutter SDK has since been upgraded to its latest version (2.1.2) which has updated Android and iOS dependencies that tackle several performance improvements and bug fixes, it would be extremely helpful if you could give this update a try and monitor your app's performance, here's a [changelog](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES) with the latest updates and here you'll find the[ integration docs](https://developer.uxcam.com/docs/flutter).
